## Instalar a extesão RestClient
# @host = 9dd5-200-132-11-251.ngrok-free.app
@host = http://localhost:8080


### Ler todos produtos
GET {{host}}/produtos


### Ler um Produto
GET {{host}}/produtos/2

# vale a pena o deletar produto??
# ### Deletar
# DELETE {{host}}/produtos/1

### ATUALIZAR
PUT {{host}}/produtos
Content-Type: application/json

{
    "id": 1, 
    "descricao": "produsdfdsfto",
    "valor": 1.99,
    "estoque": 100
}

### adicionar
POST  {{host}}/produtos
Content-Type: application/json

{
    "descricao": "produsdfdsfto",
    "valor": 1.99,
    "estoque": 100
}



## Funcionarios
### Ler funcionarios todos
GET {{host}}/funcionarios
### Ler um funcionario
GET {{host}}/funcionarios/1
### Deletar
DELETE {{host}}/funcionarios/1
### ATUALIZAR
PUT {{host}}/funcionarios
Content-Type: application/json
{
    "id": 1, 
    "nome": "Fulano de Tal",
    "cpf": "52835209000",
    "telefone": "987654321",
    "endereco": "sem endereco"  
}
### ADICIONAR
POST {{host}}/funcionarios
Content-Type: application/json
{
    "nome": "Fulano de Tal",
    "cpf": "01763917037",
    "telefone": "11111111111",
    "endereco": "sem endereco"  
}

## Clientes
### Inserir 
# gerador de cpf: 4devs.com.br/gerador_de_cpf
POST {{host}}/clientes
Content-Type: application/json
{
    "nome": "Fulano de Tal",
    "cpf": "92961800072",
    "telefone": "987654321",
    "endereco": {
        "rua": "Rua Tal",
        "bairro": "O Bairro Aqui",
        "cep": "98733334",
        "numero": "101"
    }
}
### Ler Clientes
GET {{host}}/clientes

### Ler Clientes por Id
GET {{host}}/clientes/10

### Atualizar
PUT {{host}}/clientes
Content-Type: application/json
{
    "id": 7,
    "nome": "Fernando de Tal",
    "cpf": "92961800072",
    "telefone": "987654321",
    "endereco": {
        "rua": "Rua Tal",
        "bairro": "O Bairro Aqui",
        "cep": "98733334",
        "numero": "101"
    }
}
### Deletar
DELETE {{host}}/clientes/6

## Pedidos
### Deletar Pedido
DELETE {{host}}/pedidos/2
### Ler Pedidos => erro
GET {{host}}/pedidos


# ### Inserir => bug
# POST {{host}}/pedidos
# Content-Type: application/json
# {
#     "nome": "Fulano de Tal",
#     "cpf": "92961800072",
#     "telefone": "987654321",
#     "endereco": {
#         "rua": "Rua Tal",
#         "bairro": "O Bairro Aqui",
#         "cep": "98733334",
#         "numero": "101"
#     }
# }

### Ler Pedidos
GET {{host}}/pedidos

### Ler Pedidos por Id
GET {{host}}/pedidos/25

### Inserir Pedido
POST {{host}}/pedidos
Content-Type: application/json

{
  "cliente": {
    "id": 10,
    "nome": "fernando barbosa",
    "cpf": null,
    "telefone": "987654321",
    "endereco": {
      "rua": "Rua Tal",
      "bairro": "O Bairro Aqui",
      "complemento": "Casa",
      "numero": "123",
      "cep": "98733334"
    }
  },
  "funcionario": {
    "id": 1,
    "nome": "JOÃO",
    "cpf": "98339518054",
    "endereco": "RUA QUE DÁ BUG",
    "telefone": "53999999999"
  },
  "total": 40.00,
  "items": [
    {
      "id": 1,
      "valor_atual": 10.0,
      "quantidade": 2,
      "produto": {
        "id": 1,
        "descricao": "TORRADA AMERICANA",
        "valor": 10.00,
        "estoque": 6
      }
    },
    {
      "id": 2,
      "valor_atual": 20.0,
      "quantidade": 1,
      "produto": {
        "id": 2,
        "descricao": "BAURU DE FILÉ",
        "valor": 20.00,
        "estoque": 10
      }
    }
  ]
}

### Atualizar Pedido
PUT {{host}}/pedidos
Content-Type: application/json

{
  "id": 25,
  "cliente": {
    "id": 10,
    "nome": "fernando barbosa",
    "cpf": null,
    "telefone": "987654321",
    "endereco": {
      "rua": "Rua Tal",
      "bairro": "O Bairro Aqui",
      "complemento": "Casa",
      "numero": "123",
      "cep": "98733334"
    }
  },
  "funcionario": {
    "id": 1,
    "nome": "JOÃO",
    "cpf": "98339518054",
    "endereco": "RUA QUE DÁ BUG",
    "telefone": "53999999999"
  },
  "total": 40.00,
  "items": [
    {
      "valor_atual": 20.0,
      "quantidade": 10,
      "produto": {
        "id": 2,
        "descricao": "BAURU DE FILÉ",
        "valor": 20.00,
        "estoque": 10
      }
    }
  ]
}

### Deletar Pedido
DELETE {{host}}/pedidos/20


