## Instalar a extesão RestClient
# @host = 9dd5-200-132-11-251.ngrok-free.app
@host = http://localhost:8080

## Funcionarios
### Ler funcionarios todos

GET {{host}}/funcionarios

### Ler um funcionario
GET {{host}}/funcionarios/1

### Deletar
DELETE {{host}}/funcionarios/1
### ATUALIZAR
PUT {{host}}/funcionarios
Content-Type: application/json

{
    "id": 1, 
    "nome": "Fulano de Tal",
    "cpf": "52835209000",
    "telefone": "987654321",
    "endereco": "sem endereco"  
}

### ADICIONAR
POST {{host}}/funcionarios
Content-Type: application/json

{
    
    "nome": "Fulano de Tal",
    "cpf": "01763917037",
    "telefone": "11111111111",
    "endereco": "sem endereco"  
}

# gerador de cpf: 4devs.com.br/gerador_de_cpf
POST {{host}}/funcionarios
Content-Type: application/json
{
    "id": 1,
    "nome": "Fulano de Tal",
    "cpf": "52835209000",
    "telefone": "987654321",
    "endereco": "sem endereco"  
}


## Clientes

### Inserir 
# gerador de cpf: 4devs.com.br/gerador_de_cpf
POST {{host}}/clientes
Content-Type: application/json

{
    "nome": "Fulano de Tal",
    "cpf": "92961800072",
    "telefone": "987654321",
    "endereco": {
        "rua": "Rua Tal",
        "bairro": "O Bairro Aqui",
        "cep": "98733334",
        "numero": "101"
    }
}

### Ler Clientes
GET {{host}}/clientes

### Atualizar
PUT {{host}}/clientes
Content-Type: application/json

{
    "id": 7,
    "nome": "Fernando de Tal",
    "cpf": "92961800072",
    "telefone": "987654321",
    "endereco": {
        "rua": "Rua Tal",
        "bairro": "O Bairro Aqui",
        "cep": "98733334",
        "numero": "101"
    }
}

### Deletar
DELETE {{host}}/clientes/6


## Pedidos


### Deletar Pedido => ok
DELETE {{host}}/pedidos/1

### Ler Pedidos => erro
GET {{host}}/pedidos


### Inserir  => ainda n testado
# gerador de cpf: 4devs.com.br/gerador_de_cpf
# POST {{host}}/pedidos
# Content-Type: application/json

# {
#     "nome": "Fulano de Tal",
#     "cpf": "92961800072",
#     "telefone": "987654321",
#     "endereco": {
#         "rua": "Rua Tal",
#         "bairro": "O Bairro Aqui",
#         "cep": "98733334",
#         "numero": "101"
#     }
# }


