## Funcionarios

@host = http://localhost:8080
# @host = https://5c9c-200-132-11-251.ngrok-free.app

### Ler funcionarios todos
GET {{host}}/funcionarios

### Ler um funcionario
GET {{host}}/funcionarios/2

### Deletar
DELETE {{host}}/funcionarios/1

### ATUALIZAR
PUT {{host}}/funcionarios
Content-Type: application/json

{
    "id": 1, 
    "nome": "Neymar de Tal",
    "cpf": "52835209000",
    "telefone": "987654321",
    "endereco": "sem endereco",
    "ativo": true
}

### ADICIONAR
POST {{host}}/funcionarios
Content-Type: application/json

{
    "nome": "Cacuete Amazonas",
    "cpf": "99833452000",
    "telefone": "5317658586",
    "endereco": "sem endereco"  
}
