## Funcionarios

# @host = http://localhost:8080
@host = https://5c9c-200-132-11-251.ngrok-free.app

### Ler funcionarios todos
GET {{host}}/funcionarios
### Ler um funcionario
GET {{host}}/funcionarios/1
### Deletar
DELETE {{host}}/funcionarios/1
### ATUALIZAR
PUT {{host}}/funcionarios
Content-Type: application/json

{
    "id": 1, 
    "nome": "Fulano de Tal",
    "cpf": "52835209000",
    "telefone": "987654321",
    "endereco": "sem endereco"  
}
### ADICIONAR
POST {{host}}/funcionarios
Content-Type: application/json

{
    "nome": "Fulano de Tal",
    "cpf": "17658586072",
    "telefone": "5317658586",
    "endereco": "sem endereco"  
}
