## Itens

@host = http://localhost:8080

### Ler os itens de um pedido
GET {{host}}/pedidos/1/itens

### Ler um item de um pedido
GET {{host}}/pedidos/1/itens/1

### Inserir um item em um pedido
POST {{host}}/pedidos/1/itens
Content-Type: application/json

{
    "quantidade": 8,
    "produto": {
        "id": 2
    }
}

### Atualizar um item
PUT {{host}}/pedidos/1/itens
Content-Type: application/json

{   
    "id": 1,
    "quantidade": 8,
    "produto": {
        "id": 1
    }
}

### Deletar um item de um pedido
DELETE {{host}}/pedidos/1/itens/10
