## Pedidos

@host = http://localhost:8080

### Ler todos 
GET {{host}}/pedidos

### Ler por Id
GET {{host}}/pedidos/25


// TODO: acho que o inserir pedido deveria receber somente o id de funcionario e id cliente. ou o cpf de ambos

### Inserir 
POST {{host}}/pedidos
Content-Type: application/json

{
  "cliente": {
    "id": 3,
    "nome": "Fernando Barbosa",
    "cpf": "92961800072",
    "telefone": "987654321",
    "ativo": true,
    "endereco": {
      "rua": "Rua Tal",
      "bairro": "O Bairro Aqui",
      "complemento": null,
      "numero": "101",
      "cep": "98733334"
    }
  },
  "funcionario": {
    "id": 2,
    "nome": "Robsom Hamburguer",
    "cpf": "17658586072",
    "endereco": "sem endereco",
    "telefone": "5317658586",
    "ativo": true
  },
  "total": 40.00,
  "items": [
    {
      "id": 1,
      "valor_atual": 10.0,
      "quantidade": 2,
      "produto": {
        "id": 1,
        "descricao": "TORRADA AMERICANA",
        "valor": 10.00,
        "estoque": 6
      }
    },
    {
      "id": 2,
      "valor_atual": 20.0,
      "quantidade": 1,
      "produto": {
        "id": 2,
        "descricao": "BAURU DE FILÉ",
        "valor": 20.00,
        "estoque": 10
      }
    }
  ]
}

### Atualizar Pedido
PUT {{host}}/pedidos
Content-Type: application/json

{
  "id": 25,
  "cliente": {
    "id": 10,
    "nome": "fernando barbosa",
    "cpf": null,
    "telefone": "987654321",
    "endereco": {
      "rua": "Rua Tal",
      "bairro": "O Bairro Aqui",
      "complemento": "Casa",
      "numero": "123",
      "cep": "98733334"
    }
  },
  "funcionario": {
    "id": 1,
    "nome": "JOÃO",
    "cpf": "98339518054",
    "endereco": "RUA QUE DÁ BUG",
    "telefone": "53999999999"
  },
  "total": 40.00,
  "items": [
    {
      "valor_atual": 20.0,
      "quantidade": 10,
      "produto": {
        "id": 2,
        "descricao": "BAURU DE FILÉ",
        "valor": 20.00,
        "estoque": 10
      }
    }
  ]
}

### Deletar por ID
DELETE {{host}}/pedidos/5





## Pedidos
### Deletar Pedido
DELETE {{host}}/pedidos/2
### Ler Pedidos => erro
GET {{host}}/pedidos


# ### Inserir => bug
# POST {{host}}/pedidos
# Content-Type: application/json
# {
#     "nome": "Fulano de Tal",
#     "cpf": "92961800072",
#     "telefone": "987654321",
#     "endereco": {
#         "rua": "Rua Tal",
#         "bairro": "O Bairro Aqui",
#         "cep": "98733334",
#         "numero": "101"
#     }
# }
