## Produtos

@host = http://localhost:8080
# @host = https://5c9c-200-132-11-251.ngrok-free.app


### Ler todos produtos
GET {{host}}/produtos


### Ler um Produto
GET {{host}}/produtos/2

###

DELETE {{host}}/produtos/1

### ATUALIZAR
PUT {{host}}/produtos
Content-Type: application/json

{
    "id": 1, 
    "descricao": "teste",
    "valor": 2,
    "estoque": 100,
    "ativo": true
}

### adicionar
POST  {{host}}/produtos
Content-Type: application/json

{
    "descricao": "produsdfdsfto",
    "valor": 1.99,
    "estoque": 100
}

