## Instalar a extesão RestClient
# @host = 9dd5-200-132-11-251.ngrok-free.app
@host = http://localhost:8080

# gerador de cpf: 4devs.com.br/gerador_de_cpf
POST {{host}}/clientes
Content-Type: application/json

{
    "nome": "Fulano de Tal",
    "cpf": "92961800072",
    "telefone": "987654321",
    "endereco": {
        "rua": "Rua Tal",
        "bairro": "O Bairro Aqui",
        "cep": "98733334",
        "numero": "101"
    }
}

### Ler Clientes

GET {{host}}/clientes

### Deletar

DELETE {{host}}/clientes/6